[tool.poetry]
name = "qapi-sdk"
version = "0.3.4"
description = "QAPI SDK provides a library of classes for working with Query API in your Python code."
authors = ["TheBridgeDan <97176881+TheBridgeDan@users.noreply.github.com>"]
readme = "README.md"
packages = [{ include = "qapi_sdk" }]
homepage = "https://github.com/oneaudience/data-team-qapi-sdk"
repository = "https://github.com/oneaudience/data-team-qapi-sdk"

[tool.poetry.dependencies]
python = "^3.6"
requests = "^2.27.1"
python-dotenv = "^0.20.0"
boto3 = "^1.23.10"
smart-open = "^6.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
