[tool.poetry]
name = "brew-virustotal"
version = "0.1.4"
description = "Check Homebrew formulae and casks with VirusTotal"
authors = ["Xinyuan Chen <45612704+tddschn@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/tddschn/brew-virustotal"
repository = "https://github.com/tddschn/brew-virustotal"
classifiers = [
    "Topic :: Utilities"
]
keywords = ["homebrew", "virustotal"]

[tool.poetry.scripts]
# brew-virustotal = "brew_virustotal.cli:main"
brew-vt = "brew_virustotal.cli:main"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/tddschn/brew-virustotal/issues"

[tool.poetry.dependencies]
python = "^3.10"
virustotal-tddschn = "^0.1.6"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^22.3.0"
better-exceptions = "^0.3.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
