[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "examplepro_1"
version = "1.0.1"
description = "only a test "
readme = "README.md"
authors = [{ name = "Dominik Wuttke"}]
license = { file = "LICENSE" }

[tools.setuptools]
packages = ["examplepro_1"]