name: Run and publish coverage
on: push
  # push:
    # tags:
    #   - 'v*' # Push events to matching v*, i.e. v1.0, v2.1.3

jobs:
  build-n-publish:
    name: Build and publish Python ğŸ distributions ğŸ“¦ to TestPyPI and PyPI
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Set up Python 3.6
        uses: actions/setup-python@master
        with:
          python-version: 3.6
      - run: pip install tox
      - run: tox

      - uses: codecov/codecov-action@v2
