[tool.poetry]
name = "wsrouter"
version = "0.1.0"
description = "Starlette Shared WebSocket Endpoint"
authors = ["David Morris <gypsysoftware+gitlab@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
starlette = "^0.20.1"
shortuuid = "^1.0.9"
orjson = "^3.7.1"
boltons = "^21.0.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pytest-asyncio = "^0.18.3"
pytest-cov = "^3.0.0"
requests = "^2.27.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
