[tool.poetry]
name = "flask-does-redis"
version = "0.2.2"
description = "Flask extension to easily reuse redis connection pools"
authors = ["jthop <jh@mode14.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
redis = "^4.3.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
