[tool.poetry]
name = "estimate_pi"
version = "0.1.1"
description = ""
authors = ["Chang-Goo Kim <changgoo@princeton.edu>"]

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.22.4"
matplotlib = "^3.5.2"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
jupyterlab = "^3.4.2"
mkdocs = "^1.3.0"
mkdocstrings = "^0.19.0"
mkdocs-material = "^8.3.0"
pytkdocs = {version = "^0.16.1", extras = ["numpy-style"]}
black = "^22.3.0"
mkdocstrings-python = "^0.7.0"
matplotlib = "^3.5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
