[project]
authors = [
    { name = "Monkeytale", email = "monkeytale@dwlib.com" },
]
requires-python = ">=3.10"
dependencies = [
    "click>=8.0.0",
    "identify>=2.5.0",
    "keyring>=23.5.0",
    "loguru>=0.6.0",
    "NRCLex>=3.0.0",
    "pendulum>=2.1.2",
    "python-docx>=0.8.11",
    "sh>=1.14.2",
    "textblob>=0.17.1",
    "textX>=3.0.0",
]
name = "monkeytale"
version = "0.2.1"
description = "An opinionated markup language for composing, documenting, and visualizing a novel."
readme = "README.md"
keywords = [
    "novel",
    "structure",
    "composition",
    "documentation",
    "visualization",
]
classifiers = [
    "Development Status :: 1 - Planning",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: The Unlicense (Unlicense)",
    "Operating System :: MacOS",
    "Operating System :: POSIX",
    "Programming Language :: Python :: 3.10",
    "Topic :: Documentation",
    "Topic :: Text Processing :: Linguistic",
    "Topic :: Text Processing :: Markup",
    "Topic :: Text Processing",
]

[project.urls]
homepage = "https://github.com/MLAOPDX/monkeytale/"

[project.scripts]
"@" = "monkeytale.__init__:cli"
monkeytale = "monkeytale.__init__:cli"

[project.optional-dependencies]

[build-system]
requires = [
    "pdm-pep517",
]
build-backend = "pdm.pep517.api"

[tool.pdm]
includes = []

[tool.pdm.dev-dependencies]
lint = [
    "bandit>=1.7.4",
    "black[jupyter]>=22.3.0",
    "isort>=5.10.1",
]
test = [
    "hypothesis>=6.46.1",
    "hypothesis-faker>=0.0.23",
    "pytest>=7.1.2",
]
tools = [
    "devtools>=0.8.0",
    "jupyter>=1.0.0",
]
WTF = []

[tool.semantic_release]
branch = "main"
build_command = "pip install --user pdm && pdm build"
major_on_zero = false
repository = "testpypi"
upload_to_release = true
upload_to_repository = true
version_pattern = [
    "README.md:# Monkeytale v{version}",
]
version_variable = [
    "monkeytale/__init__.py:__version__",
    "pyproject.toml:version",
]
